from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
import sys
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Prepare and train a YOLO segmentation model from the local rail_seg_v1 CVAT dataset.",
    )
    parser.add_argument("--dataset", required=True, help="Dataset generated by convert_cvat_annotations.py.")
    parser.add_argument("--out", required=True, help="Output directory for YOLO dataset, runs, predictions, and summary.")
    parser.add_argument("--model", default="yolov8n-seg.pt", help="Ultralytics model name or local .pt path.")
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--imgsz", type=int, default=1024)
    parser.add_argument("--batch", type=int, default=2)
    parser.add_argument("--device", default="0", help="Use 0 for first CUDA GPU or cpu.")
    parser.add_argument("--workers", type=int, default=0, help="Windows-safe default is 0.")
    parser.add_argument("--val-every", type=int, default=5, help="Use every Nth labeled image as validation.")
    parser.add_argument("--tile-height", type=int, default=1024, help="Vertical crop height for YOLO tiles.")
    parser.add_argument("--tile-stride", type=int, default=512, help="Vertical stride between YOLO tiles.")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--patience", type=int, default=10)
    parser.add_argument("--conf", type=float, default=0.25, help="Prediction confidence threshold.")
    parser.add_argument("--single-cls", action="store_true", help="Collapse all labels into one class during training.")
    parser.add_argument("--mosaic", type=float, default=0.0, help="Mosaic augmentation ratio. Default 0 for tiny rail datasets.")
    parser.add_argument("--prepare-only", action="store_true", help="Only create the YOLO dataset and YAML.")
    parser.add_argument("--no-predict", action="store_true", help="Skip prediction on all source images after validation.")
    return parser


def main() -> int:
    args = build_parser().parse_args()
    source_dataset = Path(args.dataset).expanduser().resolve()
    output_dir = Path(args.out).expanduser().resolve()
    yolo_dataset_dir = output_dir / "dataset"
    run_dir = output_dir / "runs"
    prediction_dir = output_dir / "predictions"
    output_dir.mkdir(parents=True, exist_ok=True)

    split = prepare_yolo_dataset(
        source_dataset=source_dataset,
        yolo_dataset_dir=yolo_dataset_dir,
        val_every=args.val_every,
        tile_height=args.tile_height,
        tile_stride=args.tile_stride,
    )
    if args.prepare_only:
        print(f"YOLO dataset: {split['yaml_path']}")
        print(
            "Source images train/val/unlabeled: "
            f"{split['source_train_count']}/{split['source_val_count']}/{split['unlabeled_count']}"
        )
        print(f"YOLO tiles train/val: {split['train_tile_count']}/{split['val_tile_count']}")
        return 0

    try:
        import torch
        from ultralytics import YOLO
    except ImportError as exc:
        raise RuntimeError(
            "YOLO training requires torch and ultralytics. Run this script with the project .yolo-venv Python."
        ) from exc

    print(f"torch: {torch.__version__}")
    print(f"cuda_available: {torch.cuda.is_available()}")
    print(f"YOLO dataset: {split['yaml_path']}")
    model = YOLO(args.model)
    model.train(
        data=str(split["yaml_path"]),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        workers=args.workers,
        project=str(run_dir),
        name="train",
        exist_ok=True,
        seed=args.seed,
        patience=args.patience,
        single_cls=args.single_cls,
        mosaic=args.mosaic,
        close_mosaic=0,
        plots=True,
        verbose=True,
    )

    best_model_path = run_dir / "train" / "weights" / "best.pt"
    trained_model = YOLO(str(best_model_path if best_model_path.exists() else args.model))
    metrics = trained_model.val(
        data=str(split["yaml_path"]),
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        workers=args.workers,
        project=str(run_dir),
        name="val",
        exist_ok=True,
        plots=True,
    )
    metrics_dict = _jsonable(getattr(metrics, "results_dict", {}))
    metrics_path = output_dir / "metrics.json"
    _write_json(metrics_path, {"split": _jsonable(split), "metrics": metrics_dict})

    if not args.no_predict:
        trained_model.predict(
            source=str(source_dataset / "images"),
            imgsz=args.imgsz,
            conf=args.conf,
            device=args.device,
            project=str(prediction_dir),
            name="all_images",
            exist_ok=True,
            save=True,
            save_txt=True,
            save_conf=True,
        )

    summary = {
        "source_dataset": str(source_dataset),
        "output_dir": str(output_dir),
        "yolo_dataset": str(yolo_dataset_dir),
        "dataset_yaml": str(split["yaml_path"]),
        "model": args.model,
        "single_cls": args.single_cls,
        "mosaic": args.mosaic,
        "best_model_path": str(best_model_path),
        "metrics_path": str(metrics_path),
        "prediction_dir": str(prediction_dir / "all_images") if not args.no_predict else None,
        "source_train_count": split["source_train_count"],
        "source_val_count": split["source_val_count"],
        "train_tile_count": split["train_tile_count"],
        "val_tile_count": split["val_tile_count"],
        "unlabeled_count": split["unlabeled_count"],
        "metrics": metrics_dict,
    }
    _write_json(output_dir / "summary.json", summary)
    print(f"Best model: {best_model_path}")
    print(f"Metrics: {metrics_path}")
    if not args.no_predict:
        print(f"Predictions: {prediction_dir / 'all_images'}")
    print(_format_metric_summary(metrics_dict))
    return 0


def prepare_yolo_dataset(
    source_dataset: Path,
    yolo_dataset_dir: Path,
    val_every: int,
    tile_height: int,
    tile_stride: int,
) -> dict[str, Any]:
    if val_every <= 1:
        raise ValueError("val_every must be greater than 1.")
    images_dir = source_dataset / "images"
    labels_dir = source_dataset / "labels"
    classes_path = source_dataset / "classes.txt"
    if not images_dir.is_dir() or not labels_dir.is_dir():
        raise FileNotFoundError("Source dataset must contain images/ and labels/ directories.")
    class_names = [line.strip() for line in classes_path.read_text(encoding="utf-8").splitlines() if line.strip()]
    if not class_names:
        raise ValueError(f"No classes found in {classes_path}")
    image_paths = sorted(path for path in images_dir.iterdir() if path.suffix.lower() in {".png", ".jpg", ".jpeg"})
    labeled: list[tuple[Path, Path]] = []
    unlabeled: list[tuple[Path, Path]] = []
    for image_path in image_paths:
        label_path = labels_dir / f"{image_path.stem}.txt"
        if label_path.exists() and label_path.read_text(encoding="utf-8").strip():
            labeled.append((image_path, label_path))
        else:
            unlabeled.append((image_path, label_path))
    if len(labeled) < 5:
        raise ValueError("At least 5 labeled images are required for YOLO training validation.")

    train_pairs: list[tuple[Path, Path]] = []
    val_pairs: list[tuple[Path, Path]] = []
    for index, pair in enumerate(labeled):
        if (index + 1) % val_every == 0:
            val_pairs.append(pair)
        else:
            train_pairs.append(pair)
    if not train_pairs or not val_pairs:
        raise ValueError("Split produced an empty train or validation subset.")

    train_tiles = _write_tiled_split(yolo_dataset_dir, "train", train_pairs, tile_height, tile_stride)
    val_tiles = _write_tiled_split(yolo_dataset_dir, "val", val_pairs, tile_height, tile_stride)

    yaml_path = yolo_dataset_dir / "rail_seg.yaml"
    yaml_path.write_text(_dataset_yaml(yolo_dataset_dir, class_names), encoding="utf-8")
    split_csv_path = yolo_dataset_dir / "split.csv"
    _write_split_csv(split_csv_path, train_tiles, val_tiles, unlabeled)
    return {
        "source_dataset": str(source_dataset),
        "yolo_dataset_dir": str(yolo_dataset_dir),
        "yaml_path": yaml_path,
        "split_csv_path": str(split_csv_path),
        "class_names": class_names,
        "source_train_count": len(train_pairs),
        "source_val_count": len(val_pairs),
        "train_tile_count": len(train_tiles),
        "val_tile_count": len(val_tiles),
        "unlabeled_count": len(unlabeled),
    }


def _write_tiled_split(
    yolo_dataset_dir: Path,
    split_name: str,
    pairs: list[tuple[Path, Path]],
    tile_height: int,
    tile_stride: int,
) -> list[dict[str, Any]]:
    if tile_height <= 0:
        raise ValueError("tile_height must be positive.")
    if tile_stride <= 0:
        raise ValueError("tile_stride must be positive.")
    image_out = yolo_dataset_dir / "images" / split_name
    label_out = yolo_dataset_dir / "labels" / split_name
    image_out.mkdir(parents=True, exist_ok=True)
    label_out.mkdir(parents=True, exist_ok=True)
    manifest_rows: list[dict[str, Any]] = []
    crop_index = 0
    for image_path, label_path in pairs:
        image = _load_image_rgb(image_path)
        width, height = image.size
        shapes = _read_yolo_polygons(label_path, width, height)
        for top in _tile_offsets(height, tile_height, tile_stride):
            bottom = min(top + tile_height, height)
            crop_h = bottom - top
            crop_rows = _crop_labels_for_window(
                shapes=shapes,
                crop_left=0,
                crop_top=top,
                crop_width=width,
                crop_height=crop_h,
            )
            if not crop_rows:
                continue
            crop_name = f"{image_path.stem}_y{top:04d}_h{crop_h:04d}.png"
            crop_label_name = f"{image_path.stem}_y{top:04d}_h{crop_h:04d}.txt"
            crop_image = image.crop((0, top, width, bottom))
            crop_image.save(image_out / crop_name)
            (label_out / crop_label_name).write_text("\n".join(crop_rows) + "\n", encoding="utf-8")
            manifest_rows.append(
                {
                    "split": split_name,
                    "crop_index": crop_index,
                    "image": str(image_out / crop_name),
                    "label": str(label_out / crop_label_name),
                    "source_image": str(image_path),
                    "source_label": str(label_path),
                    "crop_left": 0,
                    "crop_top": top,
                    "crop_width": width,
                    "crop_height": crop_h,
                    "object_count": len(crop_rows),
                }
            )
            crop_index += 1
    return manifest_rows


def _dataset_yaml(dataset_dir: Path, class_names: list[str]) -> str:
    names = "\n".join(f"  {index}: {name}" for index, name in enumerate(class_names))
    return f"""path: {dataset_dir.as_posix()}
train: images/train
val: images/val

names:
{names}
"""


def _write_split_csv(
    path: Path,
    train_rows: list[dict[str, Any]],
    val_rows: list[dict[str, Any]],
    unlabeled_pairs: list[tuple[Path, Path]],
) -> None:
    fieldnames = ["split", "crop_index", "image", "label", "source_image", "source_label", "crop_left", "crop_top", "crop_width", "crop_height", "object_count"]
    with path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        for rows in (train_rows, val_rows):
            for row in rows:
                writer.writerow(row)
        for image_path, label_path in unlabeled_pairs:
            writer.writerow(
                {
                    "split": "unlabeled",
                    "crop_index": "",
                    "image": str(image_path),
                    "label": str(label_path),
                    "source_image": str(image_path),
                    "source_label": str(label_path),
                    "crop_left": "",
                    "crop_top": "",
                    "crop_width": "",
                    "crop_height": "",
                    "object_count": 0,
                }
            )


def _format_metric_summary(metrics: dict[str, Any]) -> str:
    if not metrics:
        return "metrics: unavailable"
    keys = [
        "metrics/mAP50-95(M)",
        "metrics/mAP50(M)",
        "metrics/precision(M)",
        "metrics/recall(M)",
        "fitness",
    ]
    parts = []
    for key in keys:
        if key in metrics:
            parts.append(f"{key}={float(metrics[key]):.4f}")
    return "metrics: " + ", ".join(parts) if parts else f"metrics: {metrics}"


def _jsonable(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, dict):
        return {str(key): _jsonable(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    try:
        import numpy as np

        if isinstance(value, np.generic):
            return value.item()
        if isinstance(value, np.ndarray):
            return value.tolist()
    except Exception:
        pass
    return value


def _write_json(path: Path, payload: object) -> None:
    with path.open("w", encoding="utf-8") as fh:
        json.dump(payload, fh, ensure_ascii=False, indent=2)


def _load_image_rgb(path: Path):
    from PIL import Image

    with Image.open(path) as image:
        return image.convert("RGB")


def _read_yolo_polygons(label_path: Path, width: int, height: int) -> list[tuple[int, list[tuple[float, float]]]]:
    shapes: list[tuple[int, list[tuple[float, float]]]] = []
    if not label_path.exists():
        return shapes
    for line in label_path.read_text(encoding="utf-8").splitlines():
        parts = line.strip().split()
        if len(parts) < 7:
            continue
        class_id = int(float(parts[0]))
        values = [float(value) for value in parts[1:]]
        points = []
        for index in range(0, len(values) - 1, 2):
            x = float(values[index]) * width
            y = float(values[index + 1]) * height
            points.append((x, y))
        if len(points) >= 3:
            shapes.append((class_id, points))
    return shapes


def _tile_offsets(length: int, tile_length: int, stride: int) -> list[int]:
    if length <= tile_length:
        return [0]
    offsets = list(range(0, length - tile_length + 1, stride))
    final_offset = length - tile_length
    if offsets[-1] != final_offset:
        offsets.append(final_offset)
    return offsets


def _crop_labels_for_window(
    shapes: list[tuple[int, list[tuple[float, float]]]],
    crop_left: int,
    crop_top: int,
    crop_width: int,
    crop_height: int,
) -> list[str]:
    try:
        import cv2
        import numpy as np
    except ImportError as exc:
        raise RuntimeError("YOLO crop preparation requires opencv-python and numpy.") from exc

    crop_rows: list[str] = []
    for class_id, points in shapes:
        if not _polygon_intersects_crop(points, crop_left, crop_top, crop_width, crop_height):
            continue
        shifted = np.array([[x - crop_left, y - crop_top] for x, y in points], dtype=np.float32)
        mask = np.zeros((crop_height, crop_width), dtype=np.uint8)
        contour = np.round(shifted).astype(np.int32)
        if contour.shape[0] < 3:
            continue
        cv2.fillPoly(mask, [contour], 1)
        if not np.any(mask):
            continue
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if not contours:
            continue
        contour = max(contours, key=cv2.contourArea)
        if contour.shape[0] < 3:
            continue
        area = float(cv2.contourArea(contour))
        if area <= 16.0:
            continue
        values = [str(class_id)]
        for point in contour[:, 0, :]:
            x = float(np.clip(point[0], 0, crop_width - 1))
            y = float(np.clip(point[1], 0, crop_height - 1))
            values.append(_format_float(x / max(crop_width, 1)))
            values.append(_format_float(y / max(crop_height, 1)))
        if len(values) >= 7:
            crop_rows.append(" ".join(values))
    return crop_rows


def _polygon_intersects_crop(
    points: list[tuple[float, float]],
    crop_left: int,
    crop_top: int,
    crop_width: int,
    crop_height: int,
) -> bool:
    xs = [point[0] for point in points]
    ys = [point[1] for point in points]
    x_min = min(xs)
    x_max = max(xs)
    y_min = min(ys)
    y_max = max(ys)
    return not (
        x_max < crop_left
        or x_min > crop_left + crop_width
        or y_max < crop_top
        or y_min > crop_top + crop_height
    )


def _format_float(value: float) -> str:
    text = f"{value:.6f}".rstrip("0").rstrip(".")
    return text if text else "0"


if __name__ == "__main__":
    raise SystemExit(main())
